### ISSUE TITLE
Should we add PyQt4 support?

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#12]
It might be possible to support either PySide or PyQt4 with a certain preference order asserted.  Code such as this would be inserted as needed::

    try:
        from PySide.QtCore import *  #@UnusedWildImport
        from PySide.QtGui import *   #@UnusedWildImport
        import PySide
        pyqt_name = "PySide"
        pyqt_version = PySide.__version__
    except:
        from PyQt4.QtCore import *  #@UnusedWildImport
        from PyQt4.QtGui import *   #@UnusedWildImport
        pyqt_name = "PyQt4"
        from PyQt4.pyqtconfig import Configuration
        pyqt_version = Configuration().pyqt_version_str
    matplotlib.rcParams['backend.qt4'] = pyqt_name

**Comment by prjemian** [comment]
With the potential demise of the PySide project this year, this issue will be increase in priority

**Comment by rayosborn** [comment]
I think it's premature to talk of PySide's demise. It is skating close to the edge, but there are quite a few commercial projects, including Enthought, that would be compromised if they had to adopt the PyQt license, so I think there will be some action before the end of the year. That said, I would be happy if someone wanted to create a separate branch to explore making NeXpy agnostic. There are a couple of packages out there designed to make that possible.

**Comment by rayosborn** [comment]
PyQt4 has been supported since v0.6.0.
