### ISSUE TITLE
Problem importing __version__

### ISSUE THREAD

**Issue by mdoucet** [nexpy/nexpy#129]
Something seems to be missing from `nexpy.api.__init__`. When using `NXroot.save()`, it tries to import `__version__` from a level up and fails.

>    tree.save('test_event.nxs')
>  File "/lib/python2.7/site-packages/nexpy/api/nexus/tree.py", line 1351, in save
>    f.writefile(root)
>  File "/lib/python2.7/site-packages/nexpy/api/nexus/tree.py", line 547, in writefile
>    self._rootattrs()
>  File "/lib/python2.7/site-packages/nexpy/api/nexus/tree.py", line 729, in _rootattrs
>    from .. import `__version__`

**Comment by rayosborn** [comment]
How are you running this? I probably should have removed this version of `tree.py` from the NeXpy distribution, but it is never invoked by NeXpy itself, which instead invokes the version in the `nexusformat` package. I'll remove it before the next NeXpy release.

**Comment by mdoucet** [comment]
Interesting. I didn't realize this was meant to be deprecated. I import `api.nexus` directly in a script. `tree.py` works quite well for what I need to do.

**Comment by rayosborn** [comment]
I would recommend that you do `pip install nexusformat` or `conda install -c nexpy nexusformat`, and then do `from nexusformat.nexus import *`. The version in the `nexpy` distribution has not been updated for a couple of years.
