### ISSUE TITLE
generalize the text file import

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#14]
It is proposed to create a new text file importer that can handle a more general class of multi-column text files.  The capabilities of the importer are shown in the attached figure of the import dialog.

![import-dialog-idea](https://f.cloud.github.com/assets/2279984/1996582/746216f6-8516-11e3-85ee-3919efe398f3.png)

**Comment by rayosborn** [comment]
Although the resulting GUI is somewhat different to what is proposed here, I believe that the same functionality has been implemented in #292.

**Comment by prjemian** [comment]
Thanks!
