### ISSUE TITLE
a part of the tree menu bar freezes in the old position

### ISSUE THREAD

**Issue by jkotan** [nexpy/nexpy#149]
it is a minor issue. I've noticed that when I run it on debian stretch with gnome a part of the tree menu bar freezess in the old position

![nexpy](https://user-images.githubusercontent.com/10651163/38680528-d2308fb6-3e66-11e8-8c65-505b6299b6ee.png)

**Comment by rayosborn** [comment]
I really appreciate getting feedback, so keep the issues coming. Is this a permanent freeze, or does it correct itself if you select the upper tree item? I have seen similar behavior on my Mac as well, although I thought it only occurred with the left hand selection on the parent group and the right on a child item. I always assumed it's a quirk with PyQt, and I'm fairly sure I have no control over it. If there are any PyQt experts out there who know how to stop this happening, I would love to fix it.

**Comment by jkotan** [comment]
On the next click it was changing but not always correctly.  In my case #150 has fixed the issue.

**Comment by rayosborn** [comment]
Fixed by #150.
