### ISSUE TITLE
ValueError: values must all be positive

### ISSUE THREAD

**Issue by jkotan** [nexpy/nexpy#153]
During my tests of  `Import TIFF image`  with `v0.10.11` using [tiff](https://github.com/jkotan/file-examples/blob/master/petiff/AgBeh_GISAXS-00001.raw.tif) I went to the `signal` tab set the the `log` scale and start to change the last two combo-boxes with the color scale and ?rendering options? (maybe it would be good to add Tips in clouds what is what). After a while I got the following error:

       2018-04-13 10:40:57,737 - ERROR - Exception in GUI event loop
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    /home/jkotan/testinst/lib/python2.7/site-packages/NeXpy-0.10.10+39.g9227249.dirty-py2.7.egg/nexpy/gui/plotview.pyc in change_cmap(self)
       2884     def change_cmap(self):
       2885         """Change the color map of the current plot."""
    -> 2886         self.cmap = self.cmapcombo.currentText()
       2887 
       2888     def _cmap(self):

    /home/jkotan/testinst/lib/python2.7/site-packages/NeXpy-0.10.10+39.g9227249.dirty-py2.7.egg/nexpy/gui/plotview.pyc in _set_cmap(self, cmap)
       2910                 self.cmapcombo.setCurrentIndex(idx)
       2911             cm.set_bad('k', 1)
    -> 2912             self.plotview.image.set_cmap(cm)
       2913             if self.symmetric:
       2914                 self.symmetrize()

    /usr/lib/python2.7/dist-packages/matplotlib/image.pyc in set_cmap(self, cmap)
	192 
	193     def set_cmap(self, cmap):
    --> 194         super(_ImageBase, self).set_cmap(cmap)
	195         self.stale = True
	196 

    /usr/lib/python2.7/dist-packages/matplotlib/cm.pyc in set_cmap(self, cmap)
	320         cmap = get_cmap(cmap)
	321         self.cmap = cmap
    --> 322         self.changed()
	323 
	324     def set_norm(self, norm):

    /usr/lib/python2.7/dist-packages/matplotlib/image.pyc in changed(self)
	271         self._imcache = None
	272         self._rgbacache = None
    --> 273         cm.ScalarMappable.changed(self)
	274 
	275     def _make_image(self, A, in_bbox, out_bbox, clip_bbox, magnification=1.0,

    /usr/lib/python2.7/dist-packages/matplotlib/cm.pyc in changed(self)
	371         callbackSM listeners to the 'changed' signal
	372         """
    --> 373         self.callbacksSM.process('changed', self)
	374 
	375         for key in self.update_dict:

    /usr/lib/python2.7/dist-packages/matplotlib/cbook.pyc in process(self, s, *args, **kwargs)
	547             for cid, proxy in list(six.iteritems(self.callbacks[s])):
	548                 try:
    --> 549                     proxy(*args, **kwargs)
	550                 except ReferenceError:
	551                     self._remove_proxy(proxy)

    /usr/lib/python2.7/dist-packages/matplotlib/cbook.pyc in __call__(self, *args, **kwargs)
	414             mtd = self.func
	415         # invoke the callable and return the result
    --> 416         return mtd(*args, **kwargs)
	417 
	418     def __eq__(self, other):

    /usr/lib/python2.7/dist-packages/matplotlib/colorbar.pyc in on_mappable_changed(self, mappable)
	936         self.set_cmap(mappable.get_cmap())
	937         self.set_clim(mappable.get_clim())
    --> 938         self.update_normal(mappable)
	939 
	940     def add_lines(self, CS, erase=True):

    /usr/lib/python2.7/dist-packages/matplotlib/colorbar.pyc in update_normal(self, mappable)
	967         or contour plot to which this colorbar belongs is changed.
	968         '''
    --> 969         self.draw_all()
	970         if isinstance(self.mappable, contour.ContourSet):
	971             CS = self.mappable

    /usr/lib/python2.7/dist-packages/matplotlib/colorbar.pyc in draw_all(self)
	349         X, Y = self._mesh()
	350         C = self._values[:, np.newaxis]
    --> 351         self._config_axes(X, Y)
	352         if self.filled:
	353             self._add_solids(X, Y, C)

    /usr/lib/python2.7/dist-packages/matplotlib/colorbar.pyc in _config_axes(self, X, Y)
	445         ax.add_artist(self.patch)
	446 
    --> 447         self.update_ticks()
	448 
	449     def _set_label(self):

    /usr/lib/python2.7/dist-packages/matplotlib/colorbar.pyc in update_ticks(self)
	374         """
	375         ax = self.ax
    --> 376         ticks, ticklabels, offset_string = self._ticker()
	377         if self.orientation == 'vertical':
	378             ax.yaxis.set_ticks(ticks)

    /usr/lib/python2.7/dist-packages/matplotlib/colorbar.pyc in _ticker(self)
	612             eps = (intv[1] - intv[0]) * 1e-10
	613             b = b[(b <= intv[1] + eps) & (b >= intv[0] - eps)]
    --> 614         ticks = self._locate(b)
	615         formatter.set_locs(b)
	616         ticklabels = [formatter(t, i) for i, t in enumerate(b)]

    /usr/lib/python2.7/dist-packages/matplotlib/colorbar.pyc in _locate(self, x)
	853             # Do calculations using normalized coordinates so
	854             # as to make the interpolation more accurate.
    --> 855             b = self.norm(self._boundaries, clip=False).filled()
	856             xn = self.norm(x, clip=False).filled()
	857 

    /usr/lib/python2.7/dist-packages/matplotlib/colors.pyc in __call__(self, value, clip)
	911             raise ValueError("minvalue must be less than or equal to maxvalue")
	912         elif vmin <= 0:
    --> 913             raise ValueError("values must all be positive")
	914         elif vmin == vmax:
	915             result.fill(0)

    ValueError: values must all be positive

and then it was repeating after each change of the scale till I restart `nexpy`. But after a while I get the same error.

**Comment by rayosborn** [comment]
This seems to happen when you switch from one of the symmetric color maps, which are at the bottom of the list, back to one of the regular color maps, but I haven't yet worked out the precise systematics. I can probably use exception-handling to make sure it doesn't happen. 

By the way, you might be interested that I have added an "Open Image..." menu item to the v0.10.11 branch, which uses Fabio if it's installed. That has nothing to do with this issue, though.

**Comment by jkotan** [comment]
Yes. "Open Image..." works quite nice. I'm only not sure if it is allowed to put NXdata below NXroot.

**Comment by rayosborn** [comment]
The Images root item is not meant to be saved as a NeXus file. It is a scratch area for uploading images  as NXdata groups that are required for plotting purposes or are to be copied into other NeXus files. You can, for example, copy and paste the NXdata group into another root tree item. Putting it within an NXentry group just makes for extra typing when you access the image data from the shell. I probably need to write a section on this design philosophy in the NeXpy documentation.

**Comment by jkotan** [comment]
In this view it is OK. Thanks.

**Comment by rayosborn** [comment]
I have not encountered this particular issue, and there have been a lot of code changes since it was raised, so I will close it now. Please create another issue if a similar problem recurs.
