### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by jkotan** [nexpy/nexpy#157]
Hi,

Trying to plot data from a file [(from here)](https://github.com/jkotan/file-examples/blob/master/pninexus/testp06_cp3.nxs) by clicking `testp06_cp3.scan1234.data.exp_vfc15` in the tree view I get the following error:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    /usr/lib/python3/dist-packages/nexpy/gui/mainwindow.py in plot_data(self)
       1398                         pass
       1399                 if node.is_plottable():
    -> 1400                     dialog = PlotDialog(node, parent=self, fmt='o')
       1401                     dialog.show()
       1402                 else:

    /usr/lib/python3/dist-packages/nexpy/gui/datadialogs.py in __init__(self, node, parent, fmt)
	830         self.grid.addWidget(QtWidgets.QLabel('Signal :'), 0, 0)
	831         self.grid.addWidget(self.signal_combo, 0, 1)
    --> 832         self.choose_signal()
	833 
	834         self.layout = QtWidgets.QVBoxLayout()

    /usr/lib/python3/dist-packages/nexpy/gui/datadialogs.py in choose_signal(self)
	857             row += 1
	858             self.grid.addWidget(QtWidgets.QLabel("Axis %s: " % axis), row, 0)
    --> 859             self.axis_boxes[axis] = self.axis_box(axis)
	860             self.grid.addWidget(self.axis_boxes[axis], row, 1)
	861         while row < self.grid.rowCount() - 1:

    /usr/lib/python3/dist-packages/nexpy/gui/datadialogs.py in axis_box(self, axis)
	868         for node in self.group.values():
	869             if isinstance(node, NXfield) and node is not self.signal:
    --> 870                 if self.check_axis(node, axis):
	871                     axes.append(node.nxname)
	872                     box.addItem(node.nxname)

    /usr/lib/python3/dist-packages/nexpy/gui/datadialogs.py in check_axis(self, node, axis)
	892 
	893     def check_axis(self, node, axis):
    --> 894         if isinstance(node, NXgroup) or node.ndim > 1:
	895             return False
	896         axis_len = self.signal.shape[axis]

    /usr/lib/python3/dist-packages/nexusformat/nexus/tree.py in ndim(self)
       2921     @property
       2922     def ndim(self):
    -> 2923         return len(self.shape)
       2924 
       2925     @property

    TypeError: object of type 'NoneType' has no len() 

However, the following command in the Jupyter  widget

    testp06_cp3.scan1234.data.exp_vfc15.plot()

works well.

Is it related to the fact that a file for a file pointed by the `lambda` external link is missing?

**Comment by rayosborn** [comment]
A missing external link shouldn't matter. The problem appears to be that `lambda` has been set to None, so it has no shape set. The dialog creates a pull-down menu of potential axes to plot the signal against and checks their dimensions, whereas the command-line plot just plots the signal against the array index. I need to ensure that even a value of None has a shape in the NXfield, or at least catch the exception.

I'll raise an issue in the nexusformat package.

**Comment by rayosborn** [comment]
Actually, there's a second issue, although it didn't cause this exception. Apparently, `lambda` is a soft link to the actual external link. When I inspect `lambda` with h5py, it returns a value of `None`. You have to specifically interrogate the link, i.e., `h5_file.get('scan1234/data/lambda', getlink=True)` to discover that it is even a link. At the moment, we don't do that kind of check in the nexusformat API, since we normally use hard links. I think I had assumed that h5py would just return a valid value in all cases and I'm not sure why it doesn't for soft links. I will have to look into handling soft links, but this is, perhaps surprisingly, the first time I have encountered this issue.

**Comment by rayosborn** [comment]
This is tripping up on the unresolved link to `scan1234['data/lambda']`, _i.e._, the external link that doesn't exist. It's not being referenced directly when you access `exp_vfc15`, but NeXpy looks at the other NXfields in the same group to see if it can find any valid plotting axes. I will have to put in a check to make sure the link target can be resolved before using it.

**Comment by rayosborn** [comment]
I have tested that the merged PR above does fix the "Invalid path" error in `testp06_cp3.nxs`. Let me know if you still have problems.

**Comment by jkotan** [comment]
Thanks. Yes, it fixes the issue.

**Comment by rayosborn** [comment]
Should be fixed by #174 and #175, when using the latest development version of the nexpy/nexusformat package.
