### ISSUE TITLE
Error Plotting NXfields

### ISSUE THREAD

**Issue by krogstad** [nexpy/nexpy#212]
I'm attempting to plot an NXfield defined in the tree with other NXfields as axes using the right-click/"Plot Data" command. The desired behavior can be achieved from the command line using, eg,

NXdata(irins_70K.f1.data.data_mask,[irins_70K.f1.data.frame_number,irins_70K.f1.data.y_pixel,irins_70K.f1.data.x_pixel]).plot()

However, using the right-click "Plot Data" command and selecting the desired signal and axes yield the following error:

2019-10-30 14:09:10,231 - ERROR - Exception in GUI event loop
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/nexpy/gui/datadialogs.py in accept(self)
   1295                           title=self.signal_path)
   1296             data.nxsignal.attrs['signal_path'] = self.signal_path
-> 1297             data.plot(**self.kwargs)
   1298             super(PlotDialog, self).accept()
   1299         except NeXusError as error:

~/anaconda3/lib/python3.7/site-packages/nexusformat/nexus/tree.py in plot(self, fmt, xmin, xmax, ymin, ymax, vmin, vmax, **kwargs)
   6210 
   6211         plotview.plot(self, fmt, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, 
-> 6212                       vmin=vmin, vmax=vmax, **kwargs)
   6213 
   6214     def oplot(self, fmt='', **kwargs):

~/anaconda3/lib/python3.7/site-packages/nexpy/gui/plotview.py in plot(self, data, fmt, xmin, xmax, ymin, ymax, vmin, vmax, **opts)
    717             self.reset_log()
    718             self.x, self.y, self.v = self.get_image()
--> 719             self.plot_image(over, **opts)
    720 
    721         self.limits = (self.xaxis.min, self.xaxis.max,

~/anaconda3/lib/python3.7/site-packages/nexpy/gui/plotview.py in plot_image(self, over, **opts)
   1005             opts['origin'] = 'lower'
   1006             self.image = ax.imshow(self.v, extent=extent, cmap=self.cmap,
-> 1007                                    norm=self.norm, **opts)
   1008         else:
   1009             if self.skew is not None:

~/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1587     def inner(ax, *args, data=None, **kwargs):
   1588         if data is None:
-> 1589             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1590 
   1591         bound = new_sig.bind(ax, *args, **kwargs)

~/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    367                 f"%(removal)s.  If any parameter follows {name!r}, they "
    368                 f"should be pass as keyword, not positionally.")
--> 369         return func(*args, **kwargs)
    370 
    371     return wrapper

~/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    367                 f"%(removal)s.  If any parameter follows {name!r}, they "
    368                 f"should be pass as keyword, not positionally.")
--> 369         return func(*args, **kwargs)
    370 
    371     return wrapper

~/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, **kwargs)
   5656         im = mimage.AxesImage(self, cmap, norm, interpolation, origin, extent,
   5657                               filternorm=filternorm, filterrad=filterrad,
-> 5658                               resample=resample, **kwargs)
   5659 
   5660         im.set_data(X)

~/anaconda3/lib/python3.7/site-packages/matplotlib/image.py in __init__(self, ax, cmap, norm, interpolation, origin, extent, filternorm, filterrad, resample, **kwargs)
    855             filterrad=filterrad,
    856             resample=resample,
--> 857             **kwargs
    858         )
    859 

~/anaconda3/lib/python3.7/site-packages/matplotlib/image.py in __init__(self, ax, cmap, norm, interpolation, origin, filternorm, filterrad, resample, **kwargs)
    218         self._imcache = None
    219 
--> 220         self.update(kwargs)
    221 
    222     def __getstate__(self):

~/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py in update(self, props)
    955 
    956         with cbook._setattr_cm(self, eventson=False):
--> 957             ret = [_update_property(self, k, v) for k, v in props.items()]
    958 
    959         if len(ret):

~/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py in <listcomp>(.0)
    955 
    956         with cbook._setattr_cm(self, eventson=False):
--> 957             ret = [_update_property(self, k, v) for k, v in props.items()]
    958 
    959         if len(ret):

~/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py in _update_property(self, k, v)
    951                 if not callable(func):
    952                     raise AttributeError('{!r} object has no property {!r}'
--> 953                                          .format(type(self).__name__, k))
    954                 return func(v)
    955 

AttributeError: 'AxesImage' object has no property 'marker'

**Comment by rayosborn** [comment]
This should have been fixed by PR #213. I have installed the new versions on our cluster and at the APS.

**Comment by prjemian** [comment]
Where, specifically, at the APS?  On `/APSshare` or some place else?

**Comment by rayosborn** [comment]
I install the development version of NeXpy in a shared Anaconda distribution on Orthros, so it's not public. I hope to release v0.11.0, once we have ironed out issues like these, and will request that `/APSshare` be updated then.

**Comment by rayosborn** [comment]
Fixed by PR #213.
