### ISSUE TITLE
add scan command browser to SPEC importer

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#27]
As suggested in a comment to #26:

A future plan for the import window is to show a list of the scan commands (by scan number) and let the user select scans visually from the list, rather than specifying min and max scan numbers.

**Comment by rayosborn** [comment]
@prjemian, I am slowly cleaning up the repository in preparation for moving to Python 3-only. Do you mind if I close this, since it is obviously not high on anyone's priority list at the moment? It might also be difficult to implement if there are a lot of scans in a single SPEC file.

**Comment by prjemian** [comment]
Ok
