### ISSUE TITLE
truncation error in plots versus epoch time

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#276]
When plotting the APS storage ring current versus the epoch time (Python's `time.time()` values): serious truncation error is observed when plotting with v0.12.5.  Compare with similar plot in PyMCA v5.5.5 which shows the expected view with continuous increment of the time axis.

![Clipboard01](https://user-images.githubusercontent.com/2279984/84430414-47e5d700-abef-11ea-80a8-09c6bfd5b4f3.jpg)

Note: these values were acquired yesterday (2020-06-10) about noon-ish, local time.

**Comment by rayosborn** [comment]
This is good timing, because I made some changes in how we plot data with offsets, so it would be good to test it against other real-world examples before I release it. Can you extract the relevant group and post it here as a NeXus/HDF5 file?

**Comment by prjemian** [comment]
Attaching example NeXus/HDF5 file in zip archive.  Structure:

```
/media/sf_C_DRIVE/Users/Pete/Desktop/uascan2nxsas/nexpy276.h5 : NeXus data file
  @default = entry
  entry:NXentry
    @NX_class = NXentry
    @default = data
    data:NXdata
      @NX_class = NXdata
      @axes = EPOCH
      @signal = value
      EPOCH:NX_FLOAT64[209] = [1591811504.51273, 1591811505.012728, 1591811505.51273, '...', 1591811609.012732]
        @long_name = epoch time (s)
        @units = s
      time:NX_FLOAT64[209] = [0.0, 0.4999980926513672, 1.0, '...', 104.50000214576721]
        @long_name = time since first data (s)
        @units = s
      value:NX_FLOAT64[209] = [101.99119680160932, 101.99077692160932, 101.99152860160933, '...', 102.07074216160933]
        @long_name = aps_current
        @units = mA
```

[nexpy276.zip](https://github.com/nexpy/nexpy/files/4767199/nexpy276.zip)


Note: time = EPOCH - EPOCH[0]

**Comment by prjemian** [comment]
Context:  These are the updates to the storage ring current recorded as a separate data stream during a USAXS step scan, using Bluesky at 9-ID-C.

**Comment by prjemian** [comment]
the extractor code, recorded here for posterity:

```python
import h5py

with h5py.File("nexpy276.h5", "w") as fout:
    fout.attrs["default"] = "entry"

    nxentry = fout.create_group(fout.attrs["default"])
    nxentry.attrs["NX_class"] = "NXentry"
    nxentry.attrs["default"] = "data"

    nxdata = nxentry.create_group(nxentry.attrs["default"])
    nxdata.attrs["NX_class"] = "NXdata"
    nxdata.attrs["signal"] = "value"
    nxdata.attrs["axes"] = ["EPOCH",]

    with h5py.File("test_raw_usaxs.h5", "r") as fin:
        group = fin["/entry/instrument/bluesky_streams/aps_current_monitor/aps_current"]

        for key in "EPOCH time value".split():
            ds = nxdata.create_dataset(key, data=group[key][()])
            ds.attrs["units"] = group[key].attrs["units"]
            ds.attrs["long_name"] = group[key].attrs["long_name"]
```

**Comment by rayosborn** [comment]
This can be fixed by increasing the precision of some axis calculations to float64. The use of float32 is a historical legacy that didn't seem to cause problems until this use case, with a step size that is 10^9 smaller than the absolute value.
