### ISSUE TITLE
NameError: name 'nexus' is not defined

### ISSUE THREAD

**Issue by cucrui** [nexpy/nexpy#289]
when I follow the instruction from [NeXpy](https://www.nexusformat.org/NeXpy.html), I run this code for reading .nex file
```
from nexpy.api import nexus
a=nexus.load('./my_data.nex')
```
It comes out the error "NameError: name 'nexus' is not defined" .
The pakage I install is also follow the construction from the link.

Another error comes out when I run below code
```
from nexusformat.nexus import *
a=nxload('./data/my_data.nex')
```
It comes out the error
```
Traceback (most recent call last):                                                                                                                                        [0/854]
  File "/home/Anaconda3/envs/pytorch_env/lib/python3.7/site-packages/nexusformat/nexus/tree.py", line 451, in __init__
    self._file = self.h5.File(self._filename, mode, **kwargs)
  File "/home/Anaconda3/envs/pytorch_env/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/Anaconda3/envs/pytorch_env/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "read_spike.py", line 2, in <module>
    a=nxload('./data/p029_sort_final_01.nex.1')
  File "/home/Anaconda3/envs/pytorch_env/lib/python3.7/site-packages/nexusformat/nexus/tree.py", line 6689, in load
    with NXFile(filename, mode, **kwargs) as f:
  File "/home/Anaconda3/envs/pytorch_env/lib/python3.7/site-packages/nexusformat/nexus/tree.py", line 454, in __init__
    % self._filename)
nexusformat.nexus.tree.NeXusError: '/media/data1/qiurui/SpikingNN/data/p029_sort_final_01.nex.1' cannot be opened by h5py
```
I download .nex file from `ftp://ftp.fieldtriptoolbox.org/pub/fieldtrip/tutorial/spike/p029_sort_final_01.nex`
So I wonder whether the file lack some information or the pakage is not suitable for .nex file.

I'm trying to read neural spike data save in .nex file by this pakage. Thanks for answering the question above.

**Comment by rayosborn** [comment]
I'm afraid that you have come across some legacy documentation that I didn't know still existed. That has been out-of-date for years so I will try to get it updated quickly. The official documentation for NeXpy is at http://nexpy.github.io/nexpy/. 

Your second import was correct. The exception suggests that the HDF5 file might be corrupt or possibly that there are permission issues. Unfortunately, h5py error messages are not always that helpful in diagnosing the problem. Have you tried opening the file directly in h5py, i.e., 
```
>>> import h5py
>>> f=h5py.File('./data/my_data.nex')
```
If it won't open, then there is a problem with the file.

**Comment by cucrui** [comment]
> I'm afraid that you have come across some legacy documentation that I didn't know still existed. That has been out-of-date for years so I will try to get it updated quickly. The official documentation for NeXpy is at http://nexpy.github.io/nexpy/.
> 
> Your second import was correct. The exception suggests that the HDF5 file might be corrupt or possibly that there are permission issues. Unfortunately, h5py error messages are not always that helpful in diagnosing the problem. Have you tried opening the file directly in h5py, i.e.,
> 
> ```
> >>> import h5py
> >>> f=h5py.File('./data/my_data.nex')
> ```
> 
> If it won't open, then there is a problem with the file.

Thanks for your reply. I try to open this file by `f=h5py.File('./data/my_data.nex')`, the errors comes out. Maybe the file itself problem. 
By the way, I use command `wget ftp://ftp.fieldtriptoolbox.org/pub/fieldtrip/tutorial/spike/p029_sort_final_01.nex`, and it seems the file download successful.

**Comment by rayosborn** [comment]
I have just downloaded the file you mention. It is indeed corrupt in some way. It won't open with one of the standard HDF utilities.
```
$ h5dump p029_sort_final_01.nex 

h5dump error: unable to open file "p029_sort_final_01.nex"
```
This means the problem is not really a NeXpy issue.

**Comment by prjemian** [comment]
FWIW: That file is not an HDF5 file.  It belongs to some other software:

```sh
(bluesky_2021_2) prjemian@zap:/tmp$ file p029_sort_final_01.nex
p029_sort_final_01.nex: Biosig/NEX
```

Perhaps http://biosig.sourceforge.net/projects.html ?

**Comment by rayosborn** [comment]
Nice catch. Thanks.
