### ISSUE TITLE
Is release 1.0 on the road map?

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#291]
It appears that NeXpy is production code.  If the project releases are following https://semver.org, the release numbers indicate initial development (the major version number is still 0).  What remains to be completed before NeXpy can be released as 1.0?

**Comment by rayosborn** [comment]
I am planning to release a v1.0 fairly soon. I have just removed Python 2-compatibility code, and can probably release a v1.0.0rc1 now. I think v0.12.7 has been fairly well tested without any issues.

**Comment by prjemian** [comment]
Great!  Suggest you define a new [milestone](https://github.com/nexpy/nexpy/milestones/new), and then assign it the issues to be done to complete the milestone.

**Comment by rayosborn** [comment]
NeXpy v1.0.0 was released on Feb. 27. @prjemian, thanks for the encouragement to get it out the door.
