### ISSUE TITLE
strange error when trying to plot an image

### ISSUE THREAD

**Issue by picca** [nexpy/nexpy#32]
Hello, I have this error when playing with nexpy

Traceback (most recent call last):
  File "/home/experiences/diffabs/reguer/nexpy/src/nexpy/gui/treeview.py", line 352, in plot_data
    self.mainwindow.plot_data()
  File "/home/experiences/diffabs/reguer/nexpy/src/nexpy/gui/mainwindow.py", line 692, in plot_data
    if node:
ValueError: __len__() should return >= 0

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by rayosborn** [comment]
This is really an issue for nexpy/nexusformat rather than the nexpy/nexpy repository.
