### ISSUE TITLE
Installing under OSX Mavericks

### ISSUE THREAD

**Issue by mkoennecke** [nexpy/nexpy#44]
Hi,

I had a couple of issues installing nexpy on an OSX Mavericks. I finally succeeded. There were 
issues with my machine which I sorted by working in a virtualenv. But the pip installer failed to 
load:
- numpy
- pysegments
- pyzmq

which I had to install manually. For pyzmq I even had to build the zeromq libraries separately to 
make it work. The pyzmq installer failed with some byzantine error message. 

Best Regards,

     Mark Koennecke

**Comment by nexpy** [comment]
This issue is being closed due to inactivity. Packaging issues are a constantly moving target, so please open a new issue if you have a problem with installation.
