### ISSUE TITLE
from consoleap import _nexpy_dir shows error in PyDev

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#47]
PyDev (python editor plugin for eclipse) reports that this code in mainwindow.init_plugin_menus() is calling for an import that is not defined.

Inspecting the gui.consoleapp code, _nexpy_dir is only defined ad a global in an internal routine and is not known for this kind of import statement.

**Comment by prjemian** [comment]
easily fixed by adding this line to gui/consoleapp.py

_nexpy_dir = None

which value will be set properly at the time the import is called.

**Comment by prjemian** [comment]
will add this fix in branch spec_42

**Comment by rayosborn** [comment]
Do you think this is a bug that will affect normal usage of NeXpy, or is this something that only affects IDEs?

**Comment by prjemian** [comment]
Only the IDEs
