### ISSUE TITLE
data transformation apply when plotting data 

### ISSUE THREAD

**Issue by picca** [nexpy/nexpy#48]
Hello, I have a stack of spectrum.

now I would like to use a slider to navigate into this stack and plot the ith spectrum

Is is possible to apply a modification to the spectrum before plotting it.
I do not want to generate a new array but instead to apply my transformation each time the index of the spectrum is changed. In my case I want to remove a background but I would like also to do more complex transformations.

Is it possible ?

cheers

Frederic

**Comment by nexpy** [comment]
You might consider using the Script window to produce a script that does what you want, i.e., manipulate the data before a plot. For example, the script example in https://github.com/nexpy/nexpy/blob/master/src/nexpy/examples/scripts/chopper_plot.py shows how to produce a stack of one-dimensional plots.

If you are able to send an example of the NeXus file you want to plot, I could help produce a draft of one.

**Comment by picca** [comment]
In fact this is a stack of spectrum generated from a list of nexus files.

my question was more related to  interaction between the plot widget and the data which are plot when using the sliders.

**Comment by nexpy** [comment]
I'm not sure that I fully understand the question. The sliders interact with the Matplotlib axes after data has been plotted. It's equivalent to doing the following at the command line:

>>> ax = plt.gca()
>>> ax.set_xlim(xmin, xmax)

where xmin and xmax are the slider values. There is no interaction with the data itself.

It would be possible to create a special widget based on the current NXPlotView, in which one of the tabs had a slider that selected different spectra, and you could certainly add some preprocessing before it did each plot. But that would be a highly specialized widget. If you think there could be a general use for such a widget, I would be happy to consider it.

**Comment by picca** [comment]
> I'm not sure that I fully understand the question. The sliders interact with the Matplotlib axes after data has been plotted. It's equivalent to doing the following at the command line:

> ax = plt.gca()
> ax.set_xlim(xmin, xmax)

ok, but I fact I was thinking about a stack of spectrum.
there is a slider which allow to select a spectrum (usually) the first dimensionusing the numpy convention.
more precisely there is a play button which allow to display the stack.

> where xmin and xmax are the slider values. There is no interaction with the data itself.

> It would be possible to create a special widget based on the current NXPlotView, in which one of the tabs had a slider that selected different spectra, and you could certainly add some preprocessing before it did each plot. But that would be a highly specialized widget. If you think there could be a > general use for such a widget, I would be happy to consider it.

Yes it seems that I should design a dedicated widget for my purpose.

did you looked after guidata / guiqwt to create easily nice dialog boxes ?


Frederic

**Comment by rayosborn** [comment]
The play button plots different slices from a three-dimensional stack, so, as you suggest, this does more than just adjust the axes. If the data are plotted with Matplotlib imshow, then it calls the image object's set_data function to reset the data.

I haven't used quiqwt, although it looks interesting.

**Comment by picca** [comment]
The problem is that there is no more python binding for qwt6 and nobody maintain it  anymore... :((
