### ISSUE TITLE
data fit bug

### ISSUE THREAD

**Issue by jpcastell** [nexpy/nexpy#50]
After a new install of nexpy the Parameter(p) is not defined.

debug info:
Traceback (most recent call last):
  File "/home/jcastellan/nexpy/src/nexpy/gui/datadialogs.py", line 1295, in add_function
    parameters = [Parameter(p) for p in module.parameters]
NameError: global name 'Parameter' is not defined

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by jpcastell** [comment]
this seems to be a change in lmfit --> it can't find the import "fit_report"

**Comment by jpcastell** [comment]
seems to be an issue with an old version of lmfit

**Comment by rayosborn** [comment]
Thanks for fixing it yourself. I didn't want to make lmfit a requirement for NeXpy, so we can't enforce version updates, but we should probably have something in the installation directions stating what version you need.

**Comment by jpcastell** [comment]
the default lmfit in canopy is 0.3 way behind the current.  upgrading it
outside canopy breaks things.  I'm trying to move away from canopy to
generic linux pip install packages.

On Tue, Feb 17, 2015 at 1:26 PM, Ray Osborn <notifications@github.com>
wrote:

> Thanks for fixing it yourself. I didn't want to make lmfit a requirement
> for NeXpy, so we can't enforce version updates, but we should probably have
> something in the installation directions stating what version you need.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nexpy/nexpy/issues/50#issuecomment-74660197>.
>



-- 
John-Paul Castellan

mobile phone: +33781159511

**Comment by rayosborn** [comment]
I've started to look at Anaconda, but I haven't got PySide working yet.

**Comment by jpcastell** [comment]
yeah... just pip installing is taking some time.  i'm rebuilding everything
for Scilinux.  I haven't gotten to PySide yet.


On Tue, Feb 17, 2015 at 1:53 PM, Ray Osborn <notifications@github.com>
wrote:

> I've started to look at Anaconda, but I haven't got PySide working yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nexpy/nexpy/issues/50#issuecomment-74663146>.
>



-- 
John-Paul Castellan

mobile phone: +33781159511
