### ISSUE TITLE
project panel slicing issue

### ISSUE THREAD

**Issue by jpcastell** [nexpy/nexpy#52]
I've been going through some old x-ray data (point by point 2d-maps)

For the projection along the axis there is no check for which direction the axis go in. 

The data I have the one axis was collected from +ve to -ve.  The plot appears correctly but when you try to a cut an error occurs when it tries to sum over the reversed axis.  
![screenshot 2015-03-06 03 16 58](https://cloud.githubusercontent.com/assets/6791845/6524519/c0ace17a-c3fa-11e4-857f-fe91da736502.png)

**Comment by rayosborn** [comment]
There is more than one issue with this bug. One of them was that indexing dimension arrays was not working for monotonically decreasing dimensions. I have fixed that now in the master branch of the `nexusformat` package. The next version of NeXpy will use the `nexusformat` version of `tree.py`, not an internal one, so you will have to test it currently using the `nexusformat` branch of NeXpy. This doesn't yet fix the problem with the projection panels though.

**Comment by jpcastell** [comment]
I found another bug. I will put it in later

I've been making my own imports.  If you have an error in them it will
cause nexpy to crash. Likely it just needs a catch for working imports.

This is using the .nexpy readers in my home directory.

**Comment by rayosborn** [comment]
It catches some import errors. Are you talking about plugins or new importers?

**Comment by jpcastell** [comment]
I am making a new importer. I've done a simple test with basically an empty
reader with an error in it.  This causes the program to fail to start and
crash at the error in my personally added reader.


 /homedir/.nexpy/readers/readtest.py

I have attached the test reader with the error.  Just a simple print
statement that is incorrect.  with out that error the new import reader is
added to the menu and you can select a directory.



On Wed, Mar 18, 2015 at 7:36 PM, Ray Osborn <notifications@github.com>
wrote:

> It catches some import errors. Are you talking about plugins or new
> importers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nexpy/nexpy/issues/52#issuecomment-83114505>.
>



-- 
John-Paul Castellan

mobile phone: +33781159511

**Comment by rayosborn** [comment]
I have made a couple of changes both to the nexusformat and nexpy packages so that projections on reversed axes should now work. They are committed to the master branch.

**Comment by nexpy** [comment]
This has been fixed as of v0.6.0.
