### ISSUE TITLE
plot problem when axis range is small and values are large

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#54]
For data such as in #53 (when axis range is small and values are large), MatPlotLib simplifies the text on tick mark labels (useOffset=True is hard-coded in MPL).  Each label has a small number, which when added to the large number reported in scientific notation at the high end of the axis, gives the actual value of the tick mark label.

Such as:  -0.002  -0.002  0  0.001 0.002 0.003     1.027e1

see this: http://i.imgur.com/OdLqD.png

This is as much fun as counting in Roman numerals; it's not friendly at all.

By default, NeXpy should report the full value on axis tick marks .

Fix this when creating the plot with some variation of:
   ax.ticklabel_format(useOffset=False)

related:
https://github.com/matplotlib/matplotlib/issues/461
http://stackoverflow.com/questions/18704308/useoffset-false-in-config-file

**Comment by rayosborn** [comment]
I'm open to making that the default - I've had my own frustrations with this issue and hadn't looked to see how to correct it in matplotlib. In the meantime, you can change the behavior from the shell using:

>>> plotview.ax.ticklabel_format(useOffset=False)
>>> plotview.draw()

One longer-term goal would be to provide a graphical way to set some of these defaults. It's not high priority just now, but it might not be too difficult if it's possible to automatically enumerate the matplotlib and IPython options.

**Comment by nexpy** [comment]
This has been fixed as of v0.6.0.
