### ISSUE TITLE
AttributeError exception trace when exiting the application

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#56]
mintadmin@mintadmin-vbox ~/.../nexpy/src/nexpy $ ./nexpygui.py test_calc.h5 &
[1] 2306
test_calc.h5
mintadmin@mintadmin-vbox ~/.../nexpy/src/nexpy $ 

Choose menu: File
Choose item: Quit
Choose button: Quit
this appears on the console:

Traceback (most recent call last):
  File "/home/mintadmin/Documents/eclipse/nexpy/src/nexpy/gui/mainwindow.py", line 196, in close
    self.exec_mgr.finalize()
AttributeError: 'MainWindow' object has no attribute 'exec_mgr'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by rayosborn** [comment]
Thanks for catching that. This is part of remote execution code that should only be in another branch.

**Comment by prjemian** [comment]
I see it removed -- closing this issue
