### ISSUE TITLE
Hard links?

### ISSUE THREAD

**Issue by aaron-parsons** [nexpy/nexpy#61]
Hi,

I'm currently looking into writing some nexus files in python with an entry for the application definition for given experiments. NexPy was very attractive software for doing so except for one issue: the linking.

Ideally, I would be able to provide an alias for the original target such that the application entry has standardised names (useful for software interaction), regardless of the original motor/detector name. NexPy doesn't allow this under soft linking, and won't allow hardlinking. The functionality is in h5py, with hardlinking providing exactly what I want.

Is there any reason we can't provide this in NexPy? Or does it exist and I have just missed it?

Thanks,

Aaron

**Comment by rayosborn** [comment]
This is a historical legacy of the NeXus file format, which NeXpy is designed to support. The NeXus format officially supports both HDF4 and XML, as well as HDF5, as underlying formats, and I think soft links were the only ones supported by HDF4, although my memory may be hazy. Links are implemented using a 'target' attribute that identifies which is the parent. It's true that HDF5 does not have such a restriction. HDF4 is now deprecated by NeXus, so it may be time for us to revisit this restriction. It may be possible to get around it in NeXpy by using the nxfile attribute. If you have an NXfield, called `field` say, then `field.nxfile` references the underlying h5py File object, but I would have to think about whether linking that way has any side effects.

**Comment by prjemian** [comment]
NeXus uses *hard* links.  These can be written using the h5py interface.

**Comment by rayosborn** [comment]
Pete, that may be true, but in the NeXus standard, the link and its target had to have the same name.

**Comment by rayosborn** [comment]
I've looked into removing this restriction, and there doesn't seem to be a technical reason not to. Furthermore, the NeXus documentation doesn't seem to be particularly explicit about this. My only concern is whether someone reading the file with the NeXus C API will encounter a problem. I have implemented this on the master branch but note that you also have to update to the latest development version of the nexusformat package as well.

**Comment by prjemian** [comment]
With questioning NeXus directly.  I have not seen the restriction that the
linked item must be named identically.  If this is an explicit requirement,
it should be stated as such in the NeXus documentation.

**Comment by aaron-parsons** [comment]
Hi Ray,

Thanks for this! I'll use it first thing Monday.

I haven't seen anywhere in the nexus docs why this shouldn't be ok. In fact, not being able to change the name sort of contradicts the use of application definitions as far as I understand them ie. We want to have some standardised names in the application sub entry, rather than those which the data is collected with.

Aaron



On 3 Jul 2015, at 22:18, Ray Osborn <notifications@github.com<mailto:notifications@github.com>> wrote:


I've looked into removing this restriction, and there doesn't seem to be a technical reason not to. Furthermore, the NeXus documentation doesn't seem to be particularly explicit about this. My only concern is whether someone reading the file with the NeXus C API will encounter a problem. I have implemented this on the master branch but note that you also have to update to the latest development version of the nexusformat package as well.

�
Reply to this email directly or view it on GitHub<https://github.com/nexpy/nexpy/issues/61#issuecomment-118427317>.

-- 
This e-mail and any attachments may contain confidential, copyright and or privileged material, and are for the use of the intended addressee only. If you are not the intended addressee or an authorised recipient of the addressee please notify us of receipt by returning the e-mail and do not use, copy, retain, distribute or disclose the information in or attached to the e-mail.
Any opinions expressed within this e-mail are those of the individual and not necessarily of Diamond Light Source Ltd. 
Diamond Light Source Ltd. cannot guarantee that this e-mail or any attachments are free from viruses and we cannot accept liability for any damage which you may sustain as a result of software viruses which may be transmitted in or with the message.
Diamond Light Source Limited (company no. 4375679). Registered in England and Wales with its registered office at Diamond House, Harwell Science and Innovation Campus, Didcot, Oxfordshire, OX11 0DE, United Kingdom

**Comment by prjemian** [comment]
Exactly

**Comment by rayosborn** [comment]
This is probably one of the hazards of remembering too many obsolete discussions from ten or fifteen years ago. My recollection is that HDF4 could not handle links with different names, something to do with attaching objects to groups by tag/ref pairs rather than names, so perhaps at one time it was just assumed and nobody formalized the requirement when NXDL's were introduced. I'll post a question to the mailing list to see if someone like Mark Koennecke can solve the mystery.

**Comment by rayosborn** [comment]
So the official word is that renaming links has been formally approved by the NIAC. Thanks for raising the issue.

**Comment by aaron-parsons** [comment]
Hi Ray,

Fantastic.

Thanks for your work on this.

Aaron




On 4 Jul 2015, at 17:36, Ray Osborn <notifications@github.com<mailto:notifications@github.com>> wrote:


So the official word is that renaming links has been formally approved by the NIAC. Thanks for raising the issue.

�
Reply to this email directly or view it on GitHub<https://github.com/nexpy/nexpy/issues/61#issuecomment-118530600>.

-- 
This e-mail and any attachments may contain confidential, copyright and or privileged material, and are for the use of the intended addressee only. If you are not the intended addressee or an authorised recipient of the addressee please notify us of receipt by returning the e-mail and do not use, copy, retain, distribute or disclose the information in or attached to the e-mail.
Any opinions expressed within this e-mail are those of the individual and not necessarily of Diamond Light Source Ltd. 
Diamond Light Source Ltd. cannot guarantee that this e-mail or any attachments are free from viruses and we cannot accept liability for any damage which you may sustain as a result of software viruses which may be transmitted in or with the message.
Diamond Light Source Limited (company no. 4375679). Registered in England and Wales with its registered office at Diamond House, Harwell Science and Innovation Campus, Didcot, Oxfordshire, OX11 0DE, United Kingdom

**Comment by prjemian** [comment]
Text about links in the NeXus documentation has been revised.  See:  http://download.nexusformat.org/doc/html/design.html#links

**Comment by nexpy** [comment]
This has been fixed as of v0.6.0.
