### ISSUE TITLE
restore eclipse-relative path in pydev setup

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#62]
In ${PROJECT_DIR_NAME}/.pydevproject, the pydevpathproperty/path was set (in revision c465ca4) incorrectly.  This should be restored to ${PROJECT_DIR_NAME}/src (interesting how this was not done by revision b714d06

**Comment by prjemian** [comment]
This is a org.python.pydev.PROJECT_EXTERNAL_SOURCE_PATH and does not affect the org.python.pydev.PROJECT_SOURCE_PATH.

However, the path specified:  /home/wozniak/proj/nexusformat/src
is not general.  Should be removed from master branch.

**Comment by rayosborn** [comment]
I don't believe this is part of the NeXpy repository now.
