### ISSUE TITLE
PyQt5 compatibility

### ISSUE THREAD

**Issue by nexpy** [nexpy/nexpy#63]
Currently, NeXpy is not compatible with PyQt5. This should not be too hard to fix because the qtconsole.qtloaders module does most of the heavy lifting, but it does require some monkey-patching to add modules transferred from QtGui to QtCore back again. Also, some explicit calls to matplotlib pyqt4 backends need to be made agnostic.

**Comment by rayosborn** [comment]
A first step has been to remove claims of PyQt5 compatibility from the documentation.

**Comment by tacaswell** [comment]
The mpl `qt_compat` file takes care of most of that monkey patching.

The main issue with qt4/qt5 is that it in pyqt5 the base classes are cooperative and play will with `super` and in pyqt4 they are not.  This is the sole reason that the mpl qt4/qt5 backends are not supported from identical code bases.

**Comment by rayosborn** [comment]
Thanks for the comment. I think the way I had written things, qt_compat was incompatible with what the Jupyter qtconsole does. I assumed that it was because I was explicitly importing qt4 backends, but I hadn't looked into it carefully enough to know. NeXpy uses some PyQt modules, such as QSortFilterProxyModel that are probably not required by mpl. Do you think qt_compat would handle those as well?

**Comment by tacaswell** [comment]
I am a bit preplexed by the issues with the jupyter imports as if you use mpl, eventually `qt_compat` is going to be imported.

It looks like that is not a move mpl handles, sorry.  RiverBank really should provide a forward port version for the moved stuff.

**Comment by rayosborn** [comment]
There are some issues with using PyQt5 on a Mac (my main development environment), so I'm putting this on hold. In the meantime, an active pull request should prevent errors when both PyQt4 and PyQt5 are installed, raised in Issue #65.

**Comment by rayosborn** [comment]
This enhancement was satisfied in PR #117 and Release v0.10.0, with fixes for PyQt v5.5 error handling in Release v0.10.2.
