### ISSUE TITLE
Allow scaling of overplots

### ISSUE THREAD

**Issue by rayosborn** [nexpy/nexpy#88]
When 1D data are overplotted, it is not possible to rescale the y-values for a better comparison when, for example, they are in different units. This can be achieved from the command-line shell, but it would be good to have  GUI way of allowing two different y-scales.

**Comment by prjemian** [comment]
possibly not limited to just two y axis scales, the GUI would allow one to assign an axis to an existing scale or create a new scale

**Comment by tacaswell** [comment]
http://matplotlib.org/mpl_toolkits/axes_grid/users/overview.html#axisartist-with-parasiteaxes might be a useful example.

**Comment by rayosborn** [comment]
This has now been implemented in PR #224, released in [v0.12.2](https://github.com/nexpy/nexpy/releases/tag/v0.12.2), where a scale and offset box was added to the Customize Dialog. It's not as ambitious as the original plan, but it provides a convenient way to compare rescaled 1D plots.
