### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by jpcastell** [nexpy/nexpy#89]
with the changes to nexpy there is one small change you should make to the documentation.

For adding a file importer <http://nexpy.github.io/nexpy/readers.html>
the import line in the example code:

line 6: from IPython.external.qt import QtGui

should be changed to 

from nexpy.gui.pyqt import QtGui

**Comment by rayosborn** [comment]
Thanks for catching that. I probably need to go through more of the documentation to check for other changes, but this one is fixed.
